

COMPLETE_B3_LOGOS_MAPPING = {

    # A - A
    "AALR3.sa": "https://img.logo.dev/ticker/AALR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "ABCB4.sa": "https://img.logo.dev/ticker/ABCB4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ABEV3.sa": "https://img.logo.dev/ticker/ABEV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AERI3.sa": "https://img.logo.dev/ticker/AERI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AFLT3.sa": "https://img.logo.dev/ticker/AFLT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AGRO3.sa": "https://img.logo.dev/ticker/AGRO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AGXY3.sa": "https://img.logo.dev/ticker/AGXY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AHEB5.sa": "https://img.logo.dev/ticker/AHEB5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALLD3.sa": "https://img.logo.dev/alliedbrasil.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALOS3.sa": "https://img.logo.dev/allos.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALPA3.sa": "https://img.logo.dev/ticker/ALPA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALPA4.sa": "https://img.logo.dev/ticker/ALPA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALPK3.sa": "https://img.logo.dev/ticker/ALPK3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALUP11.sa": "https://img.logo.dev/ticker/ALUP11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALUP3.sa": "https://img.logo.dev/ticker/ALUP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ALUP4.sa": "https://img.logo.dev/ticker/ALUP11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AMAR11.sa": "https://img.logo.dev/ticker/AMAR11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AMAR3.sa": "https://img.logo.dev/ticker/AMAR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AMBP3.sa": "https://img.logo.dev/ticker/AMBP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AMER3.sa": "https://img.logo.dev/ticker/AMER3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AMOB3.sa": "https://img.logo.dev/ticker/AMOB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ANIM3.sa": "https://img.logo.dev/ticker/ANIM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ARML3.sa": "https://img.logo.dev/ticker/ARML3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ASAI3.sa": "https://img.logo.dev/ticker/ASAI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ATED3.sa": "https://img.logo.dev/ticker/ATED3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ATMP3.sa": "https://img.logo.dev/ticker/ATMP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AURE3.sa": "https://img.logo.dev/ticker/AURE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AVLL3.sa": "https://img.logo.dev/ticker/AVLL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AZEV11.sa": "https://img.logo.dev/ticker/AZEV11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AZEV3.sa": "https://img.logo.dev/ticker/AZEV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AZEV4.sa": "https://img.logo.dev/ticker/AZEV4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AZTE3.sa": "https://img.logo.dev/ticker/AZTE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AZUL4.sa": "https://img.logo.dev/ticker/AZUL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AZZA3.sa": "https://img.logo.dev/ticker/AZZA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AXIA3.sa": "https://img.logo.dev/axia.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AXIA5.sa": "https://img.logo.dev/axia.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AXIA6.sa": "https://img.logo.dev/axia.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # BDRs - Empresas Estrangeiras
    "ABUD34.sa": "https://img.logo.dev/abud.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ABTT34.sa": "https://img.logo.dev/abbott.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ABBV34.sa": "https://img.logo.dev/abbvie.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1AP34.sa": "https://img.logo.dev/autodesk.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1EG34.sa": "https://img.logo.dev/amgen.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1ES34.sa": "https://img.logo.dev/amazon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1FL34.sa": "https://img.logo.dev/aflac.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1GI34.sa": "https://img.logo.dev/agilent.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1PD34.sa": "https://img.logo.dev/airproducts.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1LB34.sa": "https://img.logo.dev/albertsons.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1RE34.sa": "https://img.logo.dev/alexandria.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BABA34.sa": "https://img.logo.dev/alibaba.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1GN34.sa": "https://img.logo.dev/allergen.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1LL34.sa": "https://img.logo.dev/alphabet.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1EN34.sa": "https://img.logo.dev/allen.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1TT34.sa": "https://img.logo.dev/att.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MOOO34.sa": "https://img.logo.dev/altria.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1CR34.sa": "https://img.logo.dev/amcor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1EE34.sa": "https://img.logo.dev/ameren.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1EP34.sa": "https://img.logo.dev/american-electric.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1OW34.sa": "https://img.logo.dev/american-tower.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1WK34.sa": "https://img.logo.dev/american-water.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1MP34.sa": "https://img.logo.dev/ameriprise.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1ME34.sa": "https://img.logo.dev/amerisource.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AMGN34.sa": "https://img.logo.dev/amgen.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1PH34.sa": "https://img.logo.dev/amphastar.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1DI34.sa": "https://img.logo.dev/analog.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1OS34.sa": "https://img.logo.dev/aon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1ON34.sa": "https://img.logo.dev/aon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1PA34.sa": "https://img.logo.dev/apache.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AAPL34.sa": "https://img.logo.dev/apple.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1MT34.sa": "https://img.logo.dev/aptiv.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ARMT34.sa": "https://img.logo.dev/arm.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1DM34.sa": "https://img.logo.dev/avantor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AWII34.sa": "https://img.logo.dev/awin.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1JG34.sa": "https://img.logo.dev/autodesk.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ASML34.sa": "https://img.logo.dev/asml.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1SU34.sa": "https://img.logo.dev/assurant.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1ZN34.sa": "https://img.logo.dev/amazon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1TM34.sa": "https://img.logo.dev/atlassian.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1TH34.sa": "https://img.logo.dev/autohome.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ADPR34.sa": "https://img.logo.dev/autodesk.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1VB34.sa": "https://img.logo.dev/avantor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "A1VY34.sa": "https://img.logo.dev/avaya.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # BDRs com B - Empresas Estrangeiras
    "B1KR34.sa": "https://img.logo.dev/berkshire.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1LL34.sa": "https://img.logo.dev/bill.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1SA34.sa": "https://img.logo.dev/bankofamerica.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BOAC34.sa": "https://img.logo.dev/boeing.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1CS34.sa": "https://img.logo.dev/broadcom.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1AX34.sa": "https://img.logo.dev/baxter.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1BT34.sa": "https://img.logo.dev/british-american-tobacco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1DX34.sa": "https://img.logo.dev/becton-dickinson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BBYY34.sa": "https://img.logo.dev/bestbuy.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BILB34.sa": "https://img.logo.dev/bilibili.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1CH34.sa": "https://img.logo.dev/blackrock.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BLAK34.sa": "https://img.logo.dev/blackstone.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BKNG34.sa": "https://img.logo.dev/booking.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1WA34.sa": "https://img.logo.dev/bristol-myers-squibb.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BOXP34.sa": "https://img.logo.dev/boston-properties.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1PP34.sa": "https://img.logo.dev/bp.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1TI34.sa": "https://img.logo.dev/british-tobacco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AVGO34.sa": "https://img.logo.dev/broadcom.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1RF34.sa": "https://img.logo.dev/brown-forman.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1AM34.sa": "https://img.logo.dev/brookfield.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "B1FC34.sa": "https://img.logo.dev/brown-forman.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # BDRs com C - Empresas Estrangeiras
    "C1AB34.sa": "https://img.logo.dev/cabot.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1OG34.sa": "https://img.logo.dev/cognex.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1PB34.sa": "https://img.logo.dev/campbell.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C2PT34.sa": "https://img.logo.dev/copart.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CNIC34.sa": "https://img.logo.dev/cigna.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CPRL34.sa": "https://img.logo.dev/copart.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CAON34.sa": "https://img.logo.dev/caesars.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1AH34.sa": "https://img.logo.dev/cardinal-health.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1RR34.sa": "https://img.logo.dev/carrier.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CRIN34.sa": "https://img.logo.dev/carnival.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1BO34.sa": "https://img.logo.dev/cboe.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1BS34.sa": "https://img.logo.dev/citizens.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1DW34.sa": "https://img.logo.dev/cdw.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1NS34.sa": "https://img.logo.dev/cognizant.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1NP34.sa": "https://img.logo.dev/cenovus.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1FI34.sa": "https://img.logo.dev/citigroup.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1HR34.sa": "https://img.logo.dev/chevron.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1BL34.sa": "https://img.logo.dev/colgate.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1HT34.sa": "https://img.logo.dev/charter.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CHDC34.sa": "https://img.logo.dev/churchill.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1IC34.sa": "https://img.logo.dev/cincinnati.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CINF34.sa": "https://img.logo.dev/cincinnati.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1TA34.sa": "https://img.logo.dev/citrix.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CSCO34.sa": "https://img.logo.dev/cisco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CTGP34.sa": "https://img.logo.dev/citigroup.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1FG34.sa": "https://img.logo.dev/cf-industries.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CLXC34.sa": "https://img.logo.dev/clorox.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CHME34.sa": "https://img.logo.dev/chemours.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1MS34.sa": "https://img.logo.dev/cms.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CTSH34.sa": "https://img.logo.dev/cognizant.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CMCS34.sa": "https://img.logo.dev/cmcsa.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1MA34.sa": "https://img.logo.dev/comerica.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1AG34.sa": "https://img.logo.dev/caterpillar.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1DI34.sa": "https://img.logo.dev/edison.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "STZB34.sa": "https://img.logo.dev/constellation.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1OO34.sa": "https://img.logo.dev/cooper.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "COPH34.sa": "https://img.logo.dev/cooper.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1LW34.sa": "https://img.logo.dev/corning.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1TV34.sa": "https://img.logo.dev/citrix.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "COWC34.sa": "https://img.logo.dev/costco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1CI34.sa": "https://img.logo.dev/crown-castle.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CSXC34.sa": "https://img.logo.dev/csx.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "C1MI34.sa": "https://img.logo.dev/cummins.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CVSH34.sa": "https://img.logo.dev/cvs.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # BDRs com D - Empresas Estrangeiras
    "DHER34.sa": "https://img.logo.dev/danaher.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1RI34.sa": "https://img.logo.dev/darden.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DEEC34.sa": "https://img.logo.dev/deere.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1EL34.sa": "https://img.logo.dev/dell.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DEAI34.sa": "https://img.logo.dev/delta.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "XRAY34.sa": "https://img.logo.dev/dentsply.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DBAG34.sa": "https://img.logo.dev/deutsche-bank.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1VN34.sa": "https://img.logo.dev/devon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DEOP34.sa": "https://img.logo.dev/diamondback.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1AN34.sa": "https://img.logo.dev/diamondback.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1LR34.sa": "https://img.logo.dev/dollar-general.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1FS34.sa": "https://img.logo.dev/dollar-tree.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DGCO34.sa": "https://img.logo.dev/dollar-general.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1OM34.sa": "https://img.logo.dev/dominion.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D2PZ34.sa": "https://img.logo.dev/dominos.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1OV34.sa": "https://img.logo.dev/dover.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1OW34.sa": "https://img.logo.dev/dow.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1HI34.sa": "https://img.logo.dev/dr-horton.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1DY34.sa": "https://img.logo.dev/duke-energy.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "D1TE34.sa": "https://img.logo.dev/duke-energy.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # BDRs com E - Empresas Estrangeiras
    "E1MN34.sa": "https://img.logo.dev/emerson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1TN34.sa": "https://img.logo.dev/eaton.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EBAY34.sa": "https://img.logo.dev/ebay.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1CL34.sa": "https://img.logo.dev/ecolab.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1CO34.sa": "https://img.logo.dev/ecopetrol.com.co?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1IX34.sa": "https://img.logo.dev/edwards.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EAIN34.sa": "https://img.logo.dev/eaton.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1MR34.sa": "https://img.logo.dev/emerson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1TR34.sa": "https://img.logo.dev/enterprise.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1OG34.sa": "https://img.logo.dev/eog.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EQIX34.sa": "https://img.logo.dev/equinix.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1QN34.sa": "https://img.logo.dev/equinix.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1QR34.sa": "https://img.logo.dev/equity-residential.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1RI34.sa": "https://img.logo.dev/estee-lauder.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1SS34.sa": "https://img.logo.dev/essilor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ELCI34.sa": "https://img.logo.dev/el-corte-ingles.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1VE34.sa": "https://img.logo.dev/everest.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1VR34.sa": "https://img.logo.dev/everest.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1SE34.sa": "https://img.logo.dev/essilor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1XP34.sa": "https://img.logo.dev/expedia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "E1XR34.sa": "https://img.logo.dev/expedia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EXXO34.sa": "https://img.logo.dev/exxon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # BDRs com F - Empresas Estrangeiras
    "FASL34.sa": "https://img.logo.dev/fastly.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1NI34.sa": "https://img.logo.dev/financial.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FFTD34.sa": "https://img.logo.dev/fifth-third.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1EC34.sa": "https://img.logo.dev/firstenergy.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1LS34.sa": "https://img.logo.dev/fleetcor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1MC34.sa": "https://img.logo.dev/fmc.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FDMO34.sa": "https://img.logo.dev/ford.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1TV34.sa": "https://img.logo.dev/fortive.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1BH34.sa": "https://img.logo.dev/franklin-templeton.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FOXC34.sa": "https://img.logo.dev/fox.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F2NV34.sa": "https://img.logo.dev/franco-nevada.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "F1RA34.sa": "https://img.logo.dev/franklin-resources.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FCXO34.sa": "https://img.logo.dev/fcx.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FMSC34.sa": "https://img.logo.dev/fms.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "GPSI34.sa": "https://img.logo.dev/gap.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1RM34.sa": "https://img.logo.dev/garmin.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GEOO34.sa": "https://img.logo.dev/ge.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1MI34.sa": "https://img.logo.dev/general-mills.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GMCO34.sa": "https://img.logo.dev/general-motors.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1PC34.sa": "https://img.logo.dev/gilead.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GPRK34.sa": "https://img.logo.dev/geopark.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GILD34.sa": "https://img.logo.dev/gilead.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1SK34.sa": "https://img.logo.dev/glaxosmithkline.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1PI34.sa": "https://img.logo.dev/global-payments.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1LL34.sa": "https://img.logo.dev/globe-life.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1FI34.sa": "https://img.logo.dev/goldman-sachs.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GSGI34.sa": "https://img.logo.dev/gs.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",


    "H1RB34.sa": "https://img.logo.dev/hrb.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HALI34.sa": "https://img.logo.dev/halliburton.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "THGI34.sa": "https://img.logo.dev/hanover.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1OG34.sa": "https://img.logo.dev/harley-davidson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1IG34.sa": "https://img.logo.dev/hartford.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1AS34.sa": "https://img.logo.dev/hasbro.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1CA34.sa": "https://img.logo.dev/hca.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1DB34.sa": "https://img.logo.dev/hdb.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1EA34.sa": "https://img.logo.dev/pepsico.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1EI34.sa": "https://img.logo.dev/heico.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HSHY34.sa": "https://img.logo.dev/hershey.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1ES34.sa": "https://img.logo.dev/hess.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1PE34.sa": "https://img.logo.dev/hpe.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1LT34.sa": "https://img.logo.dev/hilton.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1FC34.sa": "https://img.logo.dev/hologic.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HOME34.sa": "https://img.logo.dev/home-depot.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HOND34.sa": "https://img.logo.dev/honda.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1RL34.sa": "https://img.logo.dev/hormel.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1ST34.sa": "https://img.logo.dev/host-hotels.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ARNC34.sa": "https://img.logo.dev/arconic.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1SB34.sa": "https://img.logo.dev/hsb.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1TH34.sa": "https://img.logo.dev/huntington.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1UM34.sa": "https://img.logo.dev/humana.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1BA34.sa": "https://img.logo.dev/boeing.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "H1II34.sa": "https://img.logo.dev/huntington.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "I1BN34.sa": "https://img.logo.dev/ibm.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1EX34.sa": "https://img.logo.dev/iex.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1TW34.sa": "https://img.logo.dev/itw.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1FO34.sa": "https://img.logo.dev/infosys.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1RP34.sa": "https://img.logo.dev/interpublic.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ITLC34.sa": "https://img.logo.dev/intel.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1CE34.sa": "https://img.logo.dev/ice.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1HG34.sa": "https://img.logo.dev/ihg.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1PC34.sa": "https://img.logo.dev/ipg.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1FF34.sa": "https://img.logo.dev/iff.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1PH34.sa": "https://img.logo.dev/iph.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "INTU34.sa": "https://img.logo.dev/intuit.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1VZ34.sa": "https://img.logo.dev/itv.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1RM34.sa": "https://img.logo.dev/ironmountain.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
   

    "J1KH34.sa": "https://img.logo.dev/johnsoncontrols.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "J1EG34.sa": "https://img.logo.dev/jacobs.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "J1BH34.sa": "https://img.logo.dev/jb.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "JDCO34.sa": "https://img.logo.dev/jd.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "J1EF34.sa": "https://img.logo.dev/jefferies.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "J1CI34.sa": "https://img.logo.dev/jci.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "JPMC34.sa": "https://img.logo.dev/jpmorganchase.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "J1NP34.sa": "https://img.logo.dev/juniper.net?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1BF34.sa": "https://img.logo.dev/kraftheinzcompany.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1EL34.sa": "https://img.logo.dev/kellyservices.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "KMPR34.sa": "https://img.logo.dev/kemper.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1EY34.sa": "https://img.logo.dev/key.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1IM34.sa": "https://img.logo.dev/kimco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "KMIC34.sa": "https://img.logo.dev/kinder.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1LA34.sa": "https://img.logo.dev/kelloggcompany.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1SS34.sa": "https://img.logo.dev/kiss.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PHGN34.sa": "https://img.logo.dev/phillips66.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1RC34.sa": "https://img.logo.dev/kroger.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "K1TC34.sa": "https://img.logo.dev/kt.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "L1HX34.sa": "https://img.logo.dev/l3harris.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1CA34.sa": "https://img.logo.dev/lincoln.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1RC34.sa": "https://img.logo.dev/lrcx.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1WH34.sa": "https://img.logo.dev/lowe.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1VS34.sa": "https://img.logo.dev/lvs.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1EG34.sa": "https://img.logo.dev/leggett.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1DO34.sa": "https://img.logo.dev/lockheed.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1EN34.sa": "https://img.logo.dev/lennar.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LILY34.sa": "https://img.logo.dev/lilly.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1NC34.sa": "https://img.logo.dev/lincoln.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1KQ34.sa": "https://img.logo.dev/liquidity.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1YG34.sa": "https://img.logo.dev/lyondellbasell.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1OE34.sa": "https://img.logo.dev/loreal.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LOWC34.sa": "https://img.logo.dev/lowes.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "L1YB34.sa": "https://img.logo.dev/lyb.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1TB34.sa": "https://img.logo.dev/marriott.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MACY34.sa": "https://img.logo.dev/macys.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1RO34.sa": "https://img.logo.dev/marathon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1PC34.sa": "https://img.logo.dev/marathonpetroleum.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1KT34.sa": "https://img.logo.dev/marketaxess.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1TT34.sa": "https://img.logo.dev/mattel.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1MC34.sa": "https://img.logo.dev/mccormick.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1LM34.sa": "https://img.logo.dev/martinmarietta.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1AS34.sa": "https://img.logo.dev/mastercard.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1KC34.sa": "https://img.logo.dev/mckesson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MCDC34.sa": "https://img.logo.dev/mcdonalds.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1CK34.sa": "https://img.logo.dev/mckesson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MDTC34.sa": "https://img.logo.dev/medtronic.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MRCK34.sa": "https://img.logo.dev/merck.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1CH34.sa": "https://img.logo.dev/microsoft.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MUTC34.sa": "https://img.logo.dev/mutualofomaha.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MSFT34.sa": "https://img.logo.dev/microsoft.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1AA34.sa": "https://img.logo.dev/midamerica.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1UF34.sa": "https://img.logo.dev/mufg.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1CB34.sa": "https://img.logo.dev/moodys.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MDLZ34.sa": "https://img.logo.dev/mondelez.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MCOR34.sa": "https://img.logo.dev/moodys.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MOSC34.sa": "https://img.logo.dev/mosaic.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1SI34.sa": "https://img.logo.dev/motorola.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "M1SC34.sa": "https://img.logo.dev/morganstanley.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "N1DA34.sa": "https://img.logo.dev/nvidia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1GG34.sa": "https://img.logo.dev/nike.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1OV34.sa": "https://img.logo.dev/novartis.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1WG34.sa": "https://img.logo.dev/northwestern.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1TA34.sa": "https://img.logo.dev/netapp.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NETE34.sa": "https://img.logo.dev/netflix.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1WL34.sa": "https://img.logo.dev/newell.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1EM34.sa": "https://img.logo.dev/newmont.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1WS34.sa": "https://img.logo.dev/news.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1WS35.sa": "https://img.logo.dev/news.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NEXT34.sa": "https://img.logo.dev/nextdoor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1IS34.sa": "https://img.logo.dev/nielsen.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NOKI34.sa": "https://img.logo.dev/nokia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NMRH34.sa": "https://img.logo.dev/nomura.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "J1WN34.sa": "https://img.logo.dev/johnsonandjohnson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1SC34.sa": "https://img.logo.dev/norfolk.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1TR34.sa": "https://img.logo.dev/northern.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NOCG34.sa": "https://img.logo.dev/northrop.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1VS34.sa": "https://img.logo.dev/nvda.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1VO34.sa": "https://img.logo.dev/novo.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1RG34.sa": "https://img.logo.dev/nrg.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1UE34.sa": "https://img.logo.dev/nucor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NVDC34.sa": "https://img.logo.dev/nvidia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "N1XP34.sa": "https://img.logo.dev/nxp.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "OXYP34.sa": "https://img.logo.dev/oxy.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "O1DF34.sa": "https://img.logo.dev/olddominion.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "O1MC34.sa": "https://img.logo.dev/omnicom.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "O1KE34.sa": "https://img.logo.dev/onemain.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "I1XC34.sa": "https://img.logo.dev/onemain.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "O1TI34.sa": "https://img.logo.dev/onemain.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "P1AC34.sa": "https://img.logo.dev/paccar.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1KG34.sa": "https://img.logo.dev/packaging.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1HC34.sa": "https://img.logo.dev/parker.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1AY34.sa": "https://img.logo.dev/paychex.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1YC34.sa": "https://img.logo.dev/paycom.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1NR34.sa": "https://img.logo.dev/penn.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1RG34.sa": "https://img.logo.dev/progressive.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PFIZ34.sa": "https://img.logo.dev/pfizer.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PGCO34.sa": "https://img.logo.dev/proctergamble.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PHMO34.sa": "https://img.logo.dev/phillipmorris.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1SX34.sa": "https://img.logo.dev/praxair.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1NW34.sa": "https://img.logo.dev/pinnacle.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1IO34.sa": "https://img.logo.dev/pioneer.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PNCS34.sa": "https://img.logo.dev/pnc.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1KX34.sa": "https://img.logo.dev/parker.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1PG34.sa": "https://img.logo.dev/proctergamble.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1PL34.sa": "https://img.logo.dev/pulte.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1FG34.sa": "https://img.logo.dev/pfizer.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1LD34.sa": "https://img.logo.dev/pldt.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1DT34.sa": "https://img.logo.dev/pacific.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1UK34.sa": "https://img.logo.dev/pulte.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1LK34.sa": "https://img.logo.dev/telkom.co.id?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1EG34.sa": "https://img.logo.dev/pge.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1SA34.sa": "https://img.logo.dev/publicstorage.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1HM34.sa": "https://img.logo.dev/pulte.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1VH34.sa": "https://img.logo.dev/pvh.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "QCOM34.sa": "https://img.logo.dev/qualcomm.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "Q1UA34.sa": "https://img.logo.dev/qualcomm.com.co?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "Q1UE34.sa": "https://img.logo.dev/quest.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "R1LC34.sa": "https://img.logo.dev/ralphlauren.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1JF34.sa": "https://img.logo.dev/raymondjames.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1IN34.sa": "https://img.logo.dev/regeneron.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1EG34.sa": "https://img.logo.dev/republicservices.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1FC34.sa": "https://img.logo.dev/regions.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1EL34.sa": "https://img.logo.dev/realtyincome.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1SG34.sa": "https://img.logo.dev/republicservices.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1MD34.sa": "https://img.logo.dev/resmed.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RIOT34.sa": "https://img.logo.dev/riotgames.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1HI34.sa": "https://img.logo.dev/roberthalf.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1OK34.sa": "https://img.logo.dev/rockwell.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1OL34.sa": "https://img.logo.dev/rollins.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1OP34.sa": "https://img.logo.dev/roper.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ROST34.sa": "https://img.logo.dev/rossstores.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ROXO34.sa": "https://img.logo.dev/nubank.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "R1YA34.sa": "https://img.logo.dev/ryder.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SPGI34.sa": "https://img.logo.dev/spglobal.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SSFO34.sa": "https://img.logo.dev/salesforce.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BCSA34.sa": "https://img.logo.dev/santander.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SAPP34.sa": "https://img.logo.dev/sap.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1BA34.sa": "https://img.logo.dev/sabesp.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SCHW34.sa": "https://img.logo.dev/schwab.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1TX34.sa": "https://img.logo.dev/seagate.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1EA34.sa": "https://img.logo.dev/sealedair.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1RE34.sa": "https://img.logo.dev/sempra.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1BS34.sa": "https://img.logo.dev/sherwinwilliams.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SIMN34.sa": "https://img.logo.dev/simon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SRXM34.sa": "https://img.logo.dev/siriusxm.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1KM34.sa": "https://img.logo.dev/sktelecom.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1SL34.sa": "https://img.logo.dev/schlumberger.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1LG34.sa": "https://img.logo.dev/slg.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1NN34.sa": "https://img.logo.dev/smithandnephew.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1NA34.sa": "https://img.logo.dev/snap.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SNEC34.sa": "https://img.logo.dev/sony.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1OU34.sa": "https://img.logo.dev/southern.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1SN34.sa": "https://img.logo.dev/southwest.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1WK34.sa": "https://img.logo.dev/stanley.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1TT34.sa": "https://img.logo.dev/statefarm.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1TE34.sa": "https://img.logo.dev/stryker.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "STMN34.sa": "https://img.logo.dev/stmicroelectronics.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1YK34.sa": "https://img.logo.dev/sysco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1MF34.sa": "https://img.logo.dev/summit.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1YM34.sa": "https://img.logo.dev/synopsys.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1YF34.sa": "https://img.logo.dev/synovus.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1YY34.sa": "https://img.logo.dev/sysco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1RO34.sa": "https://img.logo.dev/teradyne.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TSMC34.sa": "https://img.logo.dev/tsmc.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TAKP34.sa": "https://img.logo.dev/takeda.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TPRY34.sa": "https://img.logo.dev/tapestry.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1EL34.sa": "https://img.logo.dev/telegraph.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1EC34.sa": "https://img.logo.dev/tecnologia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1FX34.sa": "https://img.logo.dev/teleflex.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TLNC34.sa": "https://img.logo.dev/telenor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T2PX34.sa": "https://img.logo.dev/twopoint.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1SS34.sa": "https://img.logo.dev/target.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TXSA34.sa": "https://img.logo.dev/texas.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1XT34.sa": "https://img.logo.dev/textron.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1JM34.sa": "https://img.logo.dev/sjm.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "P1GR34.sa": "https://img.logo.dev/progress.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "S1HW34.sa": "https://img.logo.dev/sherwinwilliams.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1SO34.sa": "https://img.logo.dev/tyson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TMOS34.sa": "https://img.logo.dev/thermofisher.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TJXC34.sa": "https://img.logo.dev/tjx.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1MU34.sa": "https://img.logo.dev/tmobile.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TMCO34.sa": "https://img.logo.dev/toyota.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1SC34.sa": "https://img.logo.dev/tractor.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "T1DG34.sa": "https://img.logo.dev/targa.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TRVC34.sa": "https://img.logo.dev/travelers.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TSNF34.sa": "https://img.logo.dev/tyson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "UBSG34.sa": "https://img.logo.dev/ubs.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "U1DR34.sa": "https://img.logo.dev/underarmour.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ULEV34.sa": "https://img.logo.dev/ulev.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "UPAC34.sa": "https://img.logo.dev/unionpacific.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "U1RI34.sa": "https://img.logo.dev/unitedhealth.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "UNHH34.sa": "https://img.logo.dev/unitedhealth.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "U1HS34.sa": "https://img.logo.dev/universalhealth.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "U1NM34.sa": "https://img.logo.dev/unum.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "UPSS34.sa": "https://img.logo.dev/ups.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "USSX34.sa": "https://img.logo.dev/ussteel.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VLOE34.sa": "https://img.logo.dev/valero.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VLYB34.sa": "https://img.logo.dev/valley.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "V1TA34.sa": "https://img.logo.dev/vantiv.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "V1RS34.sa": "https://img.logo.dev/verisign.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VERZ34.sa": "https://img.logo.dev/verizon.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VFCO34.sa": "https://img.logo.dev/vf.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "V1IP34.sa": "https://img.logo.dev/vipshop.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "V1OD34.sa": "https://img.logo.dev/vodafone.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "V1NO34.sa": "https://img.logo.dev/vonage.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "V1MC34.sa": "https://img.logo.dev/vmware.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1AB34.sa": "https://img.logo.dev/wabtec.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WALM34.sa": "https://img.logo.dev/walmart.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WGBA34.sa": "https://img.logo.dev/walgreens.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1MG34.sa": "https://img.logo.dev/warner.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1MC34.sa": "https://img.logo.dev/waste.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1SO34.sa": "https://img.logo.dev/waters.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1EC34.sa": "https://img.logo.dev/wells.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1BO34.sa": "https://img.logo.dev/weibo.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WFCO34.sa": "https://img.logo.dev/wellsfargo.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1EL34.sa": "https://img.logo.dev/western.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W2ST34.sa": "https://img.logo.dev/westpharma.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WABC34.sa": "https://img.logo.dev/wabco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WUNI34.sa": "https://img.logo.dev/willis.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1YC34.sa": "https://img.logo.dev/wyckoff.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1HR34.sa": "https://img.logo.dev/whirlpool.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1MB34.sa": "https://img.logo.dev/williams.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1LT34.sa": "https://img.logo.dev/willis.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1PP34.sa": "https://img.logo.dev/wpp.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1RB34.sa": "https://img.logo.dev/warner.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "G1WW34.sa": "https://img.logo.dev/ww.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "W1YN34.sa": "https://img.logo.dev/wynn.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    "X1EL34.sa": "https://img.logo.dev/xcel.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "X1YL34.sa": "https://img.logo.dev/xylem.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "YUMR34.sa": "https://img.logo.dev/yum.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "Z1BH34.sa": "https://img.logo.dev/berkshire.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "Z1IO34.sa": "https://img.logo.dev/zoom.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "Z1TS34.sa": "https://img.logo.dev/zts.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "Z1TO34.sa": "https://img.logo.dev/zto.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ACNB34.sa": "https://img.logo.dev/acciona.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AIGB34.sa": "https://img.logo.dev/aig.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "AXPB34.sa": "https://img.logo.dev/americanexpress.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ATTB34.sa": "https://img.logo.dev/att.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BONY34.sa": "https://img.logo.dev/bankofnewyork.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMYB34.sa": "https://img.logo.dev/bristolmyers.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DUKB34.sa": "https://img.logo.dev/duke.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DDNB34.sa": "https://img.logo.dev/dupont.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FDXB34.sa": "https://img.logo.dev/fedex.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FMXB34.sa": "https://img.logo.dev/fomento.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GDBR34.sa": "https://img.logo.dev/goodyear.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HONB34.sa": "https://img.logo.dev/honeywell.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HPQB34.sa": "https://img.logo.dev/hpq.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "IBMB34.sa": "https://img.logo.dev/ibm.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "JNJB34.sa": "https://img.logo.dev/johnsonandjohnson.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "KMBB34.sa": "https://img.logo.dev/kimberlyclark.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "KHCB34.sa": "https://img.logo.dev/kraftheinz.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LMTB34.sa": "https://img.logo.dev/lockheed.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "METB34.sa": "https://img.logo.dev/metlife.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MSBR34.sa": "https://img.logo.dev/morganstanley.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PEPB34.sa": "https://img.logo.dev/pepsico.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SBUB34.sa": "https://img.logo.dev/starbucks.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TGTB34.sa": "https://img.logo.dev/target.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TEXA34.sa": "https://img.logo.dev/texas.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VISA34.sa": "https://img.logo.dev/visa.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DISB34.sa": "https://img.logo.dev/disney.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "XRXB34.sa": "https://img.logo.dev/xerox.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CATP34.sa": "https://img.logo.dev/caterpillar.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CHVX34.sa": "https://img.logo.dev/chevron.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "COCA34.sa": "https://img.logo.dev/coca-cola.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "COLG34.sa": "https://img.logo.dev/colgate.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MSCD34.sa": "https://img.logo.dev/mastercard.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NIKE34.sa": "https://img.logo.dev/nike.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ORCL34.sa": "https://img.logo.dev/oracle.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RYTT34.sa": "https://img.logo.dev/ryder.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SLBG34.sa": "https://img.logo.dev/schlumberger.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "USBC34.sa": "https://img.logo.dev/usbank.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "XPBR31.sa": "https://img.logo.dev/xp.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "STLA.sa": "https://img.logo.dev/stellantis.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TLK.sa": "https://img.logo.dev/telkom.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # B - B
    "B3SA3.sa": "https://img.logo.dev/ticker/B3SA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BALM3.sa": "https://img.logo.dev/ticker/BALM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BALM4.sa": "https://img.logo.dev/ticker/BALM4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BAUH4.sa": "https://img.logo.dev/ticker/BAUH4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BAZA3.sa": "https://img.logo.dev/ticker/BAZA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BBAS3.sa": "https://img.logo.dev/ticker/BBAS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BBDC3.sa": "https://img.logo.dev/ticker/BBDC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BBDC4.sa": "https://img.logo.dev/ticker/BBDC4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BBSE3.sa": "https://img.logo.dev/ticker/BBSE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BDLL3.sa": "https://img.logo.dev/ticker/BDLL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BDLL4.sa": "https://img.logo.dev/ticker/BDLL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BEEF3.sa": "https://img.logo.dev/ticker/BEEF3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BEES3.sa": "https://img.logo.dev/ticker/BEES3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BEES4.sa": "https://img.logo.dev/ticker/BEES4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BGIP3.sa": "https://img.logo.dev/ticker/BGIP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BGIP4.sa": "https://img.logo.dev/ticker/BGIP4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BHIA3.sa": "https://img.logo.dev/ticker/BHIA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BIED3.sa": "https://img.logo.dev/ticker/BIED3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BIOM3.sa": "https://img.logo.dev/ticker/BIOM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BLAU3.sa": "https://img.logo.dev/ticker/BLAU3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMEB3.sa": "https://img.logo.dev/ticker/BMEB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMEB4.sa": "https://img.logo.dev/ticker/BMEB4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMGB4.sa": "https://img.logo.dev/ticker/BMGB4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMIN3.sa": "https://img.logo.dev/ticker/BMIN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMIN4.sa": "https://img.logo.dev/ticker/BMIN4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMKS3.sa": "https://img.logo.dev/ticker/BMKS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BMOB3.sa": "https://img.logo.dev/ticker/BMOB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BNBR3.sa": "https://img.logo.dev/ticker/BNBR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BOBR4.sa": "https://img.logo.dev/ticker/BOBR4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BPAC11.sa": "https://img.logo.dev/ticker/BPAC11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BPAC3.sa": "https://img.logo.dev/ticker/BPAC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BPAC5.sa": "https://img.logo.dev/ticker/BPAC5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BPAN4.sa": "https://img.logo.dev/ticker/BPAN4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRAP3.sa": "https://img.logo.dev/ticker/BRAP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRAP4.sa": "https://img.logo.dev/bradesco.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRAV3.sa": "https://img.logo.dev/bravaenergia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRBI11.sa": "https://img.logo.dev/ticker/BRBI11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRBI3.sa": "https://img.logo.dev/ticker/BRBI11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRBI4.sa": "https://img.logo.dev/ticker/BRBI11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRFS3.sa": "https://img.logo.dev/ticker/BRFS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRKM3.sa": "https://img.logo.dev/ticker/BRKM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRKM5.sa": "https://img.logo.dev/ticker/BRKM5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRKM6.sa": "https://img.logo.dev/ticker/BRKM6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRSR3.sa": "https://img.logo.dev/ticker/BRSR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRSR5.sa": "https://img.logo.dev/ticker/BRSR5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRSR6.sa": "https://img.logo.dev/ticker/BRSR6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BRST3.sa": "https://img.logo.dev/ticker/BRST3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BSLI3.sa": "https://img.logo.dev/ticker/BSLI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BSLI4.sa": "https://img.logo.dev/ticker/BSLI4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # C - C
    "CAMB3.sa": "https://img.logo.dev/ticker/CAMB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CAML3.sa": "https://img.logo.dev/ticker/CAML3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CASH3.sa": "https://img.logo.dev/ticker/CASH3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CBAV3.sa": "https://img.logo.dev/ticker/CBAV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CBEE3.sa": "https://img.logo.dev/enel.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CCTY3.sa": "https://img.logo.dev/ticker/CCTY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CEAB3.sa": "https://img.logo.dev/ticker/CEAB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CEBR3.sa": "https://img.logo.dev/ticker/CEBR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CEBR5.sa": "https://img.logo.dev/ticker/CEBR5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CEBR6.sa": "https://img.logo.dev/ticker/CEBR6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CEDO4.sa": "https://img.logo.dev/ticker/CEDO4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CEEB3.sa": "https://img.logo.dev/ticker/CEEB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CGAS3.sa": "https://img.logo.dev/ticker/CGAS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CGAS5.sa": "https://img.logo.dev/ticker/CGAS5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CGRA3.sa": "https://img.logo.dev/ticker/CGRA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CGRA4.sa": "https://img.logo.dev/ticker/CGRA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CLSC3.sa": "https://img.logo.dev/ticker/CLSC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CLSC4.sa": "https://img.logo.dev/ticker/CLSC4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CMIG3.sa": "https://img.logo.dev/ticker/CMIG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CMIG4.sa": "https://img.logo.dev/ticker/CMIG4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CMIN3.sa": "https://img.logo.dev/ticker/CMIN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "COCE3.sa": "https://img.logo.dev/ticker/COCE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "COCE5.sa": "https://img.logo.dev/ticker/COCE5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "COGN3.sa": "https://img.logo.dev/ticker/COGN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CPFE3.sa": "https://img.logo.dev/ticker/CPFE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CPLE3.sa": "https://img.logo.dev/ticker/CPLE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CPLE5.sa": "https://img.logo.dev/ticker/CPLE5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CPLE6.sa": "https://img.logo.dev/ticker/CPLE6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CRFB3.sa": "https://img.logo.dev/ticker/CRFB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CRPG3.sa": "https://img.logo.dev/ticker/CRPG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CRPG5.sa": "https://img.logo.dev/ticker/CRPG5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CRPG6.sa": "https://img.logo.dev/ticker/CRPG6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CSAN3.sa": "https://img.logo.dev/ticker/CSAN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CSED3.sa": "https://img.logo.dev/ticker/CSED3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CSMG3.sa": "https://img.logo.dev/ticker/CSMG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CSNA3.sa": "https://img.logo.dev/ticker/CSNA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CSUD3.sa": "https://img.logo.dev/csu.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CTKA3.sa": "https://img.logo.dev/ticker/CTKA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CTKA4.sa": "https://img.logo.dev/ticker/CTKA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CTSA3.sa": "https://img.logo.dev/ticker/CTSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CTSA4.sa": "https://img.logo.dev/ticker/CTSA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CURY3.sa": "https://img.logo.dev/ticker/CURY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CVCB3.sa": "https://img.logo.dev/ticker/CVCB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CXSE3.sa": "https://img.logo.dev/ticker/CXSE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "CYRE3.sa": "https://img.logo.dev/ticker/CYRE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # D - D
    "DASA3.sa": "https://img.logo.dev/ticker/DASA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DESK3.sa": "https://img.logo.dev/ticker/DESK3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DEXP3.sa": "https://img.logo.dev/ticker/DEXP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DEXP4.sa": "https://img.logo.dev/ticker/DEXP4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DIRR3.sa": "https://img.logo.dev/ticker/DIRR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DMVF3.sa": "https://img.logo.dev/ticker/DMVF3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DOHL3.sa": "https://img.logo.dev/ticker/DOHL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DOHL4.sa": "https://img.logo.dev/ticker/DOHL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DOTZ3.sa": "https://img.logo.dev/ticker/DOTZ3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DTCY3.sa": "https://img.logo.dev/ticker/DTCY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "DXCO3.sa": "https://img.logo.dev/ticker/DXCO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # E - E
    "EALT3.sa": "https://img.logo.dev/ticker/EALT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EALT4.sa": "https://img.logo.dev/ticker/EALT4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ECOR3.sa": "https://img.logo.dev/ticker/ECOR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EGIE3.sa": "https://img.logo.dev/ticker/EGIE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EKTR3.sa": "https://img.logo.dev/ticker/EKTR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EKTR4.sa": "https://img.logo.dev/ticker/EKTR4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ELET3.sa": "https://img.logo.dev/ticker/ELET3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ELET6.sa": "https://img.logo.dev/ticker/ELET6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ELMD3.sa": "https://img.logo.dev/ticker/ELMD3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EMAE4.sa": "https://img.logo.dev/ticker/EMAE4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EMBR3.sa": "https://img.logo.dev/ticker/EMBR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ENEV3.sa": "https://img.logo.dev/ticker/ENEV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ENGI11.sa": "https://img.logo.dev/ticker/ENGI11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ENGI3.sa": "https://img.logo.dev/ticker/ENGI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ENGI4.sa": "https://img.logo.dev/ticker/ENGI4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ENJU3.sa": "https://img.logo.dev/ticker/ENJU3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ENMT3.sa": "https://img.logo.dev/energisa.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ENMT4.sa": "https://img.logo.dev/energisa.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EPAR3.sa": "https://img.logo.dev/ticker/EPAR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EQMA3B.sa": "https://img.logo.dev/ticker/EQMA3B.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EQPA3.sa": "https://img.logo.dev/ticker/EQPA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EQTL3.sa": "https://img.logo.dev/ticker/EQTL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ESPA3.sa": "https://img.logo.dev/ticker/ESPA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ESTR4.sa": "https://img.logo.dev/ticker/ESTR4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ETER3.sa": "https://img.logo.dev/ticker/ETER3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EUCA3.sa": "https://img.logo.dev/ticker/EUCA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EUCA4.sa": "https://img.logo.dev/ticker/EUCA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EVEN3.sa": "https://img.logo.dev/ticker/EVEN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "EZTC3.sa": "https://img.logo.dev/ticker/EZTC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # F - F
    "FESA3.sa": "https://img.logo.dev/ticker/FESA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FESA4.sa": "https://img.logo.dev/ticker/FESA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FHER3.sa": "https://img.logo.dev/ticker/FHER3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FICT3.sa": "https://img.logo.dev/ticker/FICT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FIEI3.sa": "https://img.logo.dev/ticker/FIEI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FIQE3.sa": "https://img.logo.dev/ticker/FIQE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FLRY3.sa": "https://img.logo.dev/ticker/FLRY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FRAS3.sa": "https://img.logo.dev/ticker/FRAS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "FRIO3.sa": "https://img.logo.dev/ticker/FRIO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # G - G
    "GEPA3.sa": "https://img.logo.dev/ticker/GEPA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GEPA4.sa": "https://img.logo.dev/ticker/GEPA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GFSA3.sa": "https://img.logo.dev/ticker/GFSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GGBR3.sa": "https://img.logo.dev/ticker/GGBR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GGBR4.sa": "https://img.logo.dev/ticker/GGBR4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GGPS3.sa": "https://img.logo.dev/ticker/GGPS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GMAT3.sa": "https://img.logo.dev/ticker/GMAT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GOAU3.sa": "https://img.logo.dev/ticker/GOAU3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GOAU4.sa": "https://img.logo.dev/ticker/GOAU4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GOLL4.sa": "https://img.logo.dev/ticker/GOLL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GPAR3.sa": "https://img.logo.dev/ticker/GPAR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GRND3.sa": "https://img.logo.dev/ticker/GRND3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GSHP3.sa": "https://img.logo.dev/ticker/GSHP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "GUAR3.sa": "https://img.logo.dev/ticker/GUAR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # H - H
    "HAGA3.sa": "https://img.logo.dev/ticker/HAGA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HAGA4.sa": "https://img.logo.dev/ticker/HAGA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HAPV3.sa": "https://img.logo.dev/ticker/HAPV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HBOR3.sa": "https://img.logo.dev/ticker/HBOR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HBRE3.sa": "https://img.logo.dev/ticker/HBRE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HBSA3.sa": "https://img.logo.dev/ticker/HBSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HBTS5.sa": "https://img.logo.dev/ticker/HBTS5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HETA4.sa": "https://img.logo.dev/ticker/HETA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HOOT4.sa": "https://img.logo.dev/ticker/HOOT4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "HYPE3.sa": "https://img.logo.dev/ticker/HYPE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # I - I
    "IFCM3.sa": "https://img.logo.dev/ticker/IFCM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "IGTI11.sa": "https://img.logo.dev/ticker/IGTI11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "IGTI3.sa": "https://img.logo.dev/ticker/IGTI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "INEP3.sa": "https://img.logo.dev/ticker/INEP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "INEP4.sa": "https://img.logo.dev/ticker/INEP4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "INTB3.sa": "https://img.logo.dev/ticker/INTB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "IRBR3.sa": "https://img.logo.dev/ticker/IRBR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ISAE3.sa": "https://img.logo.dev/isaenergia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ISAE4.sa": "https://img.logo.dev/isaenergia.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ITSA3.sa": "https://img.logo.dev/ticker/ITSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ITSA4.sa": "https://img.logo.dev/ticker/ITSA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ITUB3.sa": "https://img.logo.dev/ticker/ITUB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ITUB4.sa": "https://img.logo.dev/ticker/ITUB4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # J - J
    "JALL3.sa": "https://img.logo.dev/ticker/JALL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "JBSS3.sa": "https://img.logo.dev/ticker/JBSS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "JFEN3.sa": "https://img.logo.dev/ticker/JFEN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "JHSF3.sa": "https://img.logo.dev/ticker/JHSF3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "JSLG3.sa": "https://img.logo.dev/ticker/JSLG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # K - K
    "KEPL3.sa": "https://img.logo.dev/ticker/KEPL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "KLBN11.sa": "https://img.logo.dev/ticker/KLBN11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "KLBN3.sa": "https://img.logo.dev/ticker/KLBN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "KLBN4.sa": "https://img.logo.dev/ticker/KLBN4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # L - L
    "LAND3.sa": "https://img.logo.dev/ticker/LAND3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LAVV3.sa": "https://img.logo.dev/ticker/LAVV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LEVE3.sa": "https://img.logo.dev/ticker/LEVE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LIGT3.sa": "https://img.logo.dev/ticker/LIGT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LIPR3.sa": "https://img.logo.dev/ticker/LIPR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LJQQ3.sa": "https://img.logo.dev/ticker/LJQQ3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LOGG3.sa": "https://img.logo.dev/ticker/LOGG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LOGN3.sa": "https://img.logo.dev/ticker/LOGN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LPSB3.sa": "https://img.logo.dev/ticker/LPSB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LREN3.sa": "https://img.logo.dev/ticker/LREN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LUPA3.sa": "https://img.logo.dev/ticker/LUPA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LUXM4.sa": "https://img.logo.dev/ticker/LUXM4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LVTC3.sa": "https://img.logo.dev/ticker/LVTC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "LWSA3.sa": "https://img.logo.dev/ticker/LWSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # M - M
    "MAPT3.sa": "https://img.logo.dev/ticker/MAPT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MATD3.sa": "https://img.logo.dev/ticker/MATD3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MBLY3.sa": "https://img.logo.dev/ticker/MBLY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MDIA3.sa": "https://img.logo.dev/ticker/MDIA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MDNE3.sa": "https://img.logo.dev/ticker/MDNE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MEAL3.sa": "https://img.logo.dev/ticker/MEAL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MELK3.sa": "https://img.logo.dev/ticker/MELK3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MGEL4.sa": "https://img.logo.dev/ticker/MGEL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MGLU3.sa": "https://img.logo.dev/ticker/MGLU3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MILS3.sa": "https://img.logo.dev/ticker/MILS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MLAS3.sa": "https://img.logo.dev/ticker/MLAS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MNDL3.sa": "https://img.logo.dev/ticker/MNDL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MNPR3.sa": "https://img.logo.dev/ticker/MNPR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MOAR3.sa": "https://img.logo.dev/ticker/MOAR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MOTV3.sa": "https://img.logo.dev/motiva.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MOVI3.sa": "https://img.logo.dev/ticker/MOVI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MRFG3.sa": "https://img.logo.dev/ticker/MRFG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MRSA3B.sa": "https://img.logo.dev/ticker/MRSA3B.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MRVE3.sa": "https://img.logo.dev/ticker/MRVE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MTRE3.sa": "https://img.logo.dev/ticker/MTRE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MTSA3.sa": "https://img.logo.dev/ticker/MTSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MTSA4.sa": "https://img.logo.dev/ticker/MTSA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MULT3.sa": "https://img.logo.dev/ticker/MULT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MWET4.sa": "https://img.logo.dev/ticker/MWET4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "MYPK3.sa": "https://img.logo.dev/ticker/MYPK3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # N - N
    "NEOE3.sa": "https://img.logo.dev/ticker/NEOE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NEXP3.sa": "https://img.logo.dev/ticker/NEXP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NGRD3.sa": "https://img.logo.dev/ticker/NGRD3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NORD3.sa": "https://img.logo.dev/ticker/NORD3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NTCO3.sa": "https://img.logo.dev/ticker/NTCO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "NUTR3.sa": "https://img.logo.dev/ticker/NUTR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # O - O
    "ODPV3.sa": "https://img.logo.dev/ticker/ODPV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "OFSA3.sa": "https://img.logo.dev/ticker/OFSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "OIBR3.sa": "https://img.logo.dev/ticker/OIBR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "OIBR4.sa": "https://img.logo.dev/ticker/OIBR4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ONCO3.sa": "https://img.logo.dev/ticker/ONCO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "OPCT3.sa": "https://img.logo.dev/ticker/OPCT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ORVR3.sa": "https://img.logo.dev/ticker/ORVR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "OSXB3.sa": "https://img.logo.dev/ticker/OSXB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # P - P
    "PATI3.sa": "https://img.logo.dev/ticker/PATI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PATI4.sa": "https://img.logo.dev/ticker/PATI4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PCAR3.sa": "https://img.logo.dev/ticker/PCAR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PDGR3.sa": "https://img.logo.dev/ticker/PDGR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PDTC3.sa": "https://img.logo.dev/ticker/PDTC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PEAB3.sa": "https://img.logo.dev/ticker/PEAB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PEAB4.sa": "https://img.logo.dev/ticker/PEAB4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PETR3.sa": "https://img.logo.dev/ticker/PETR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PETR4.sa": "https://img.logo.dev/ticker/PETR4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PETZ3.sa": "https://img.logo.dev/ticker/PETZ3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PFRM3.sa": "https://img.logo.dev/ticker/PFRM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PGMN3.sa": "https://img.logo.dev/ticker/PGMN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PINE11.sa": "https://img.logo.dev/ticker/PINE11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PINE3.sa": "https://img.logo.dev/ticker/PINE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PINE4.sa": "https://img.logo.dev/pine.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PLAS3.sa": "https://img.logo.dev/ticker/PLAS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PLPL3.sa": "https://img.logo.dev/ticker/PLPL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PMAM3.sa": "https://img.logo.dev/ticker/PMAM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PNVL3.sa": "https://img.logo.dev/ticker/PNVL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "POMO3.sa": "https://img.logo.dev/ticker/POMO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "POMO4.sa": "https://img.logo.dev/ticker/POMO4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PORT3.sa": "https://img.logo.dev/ticker/PORT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "POSI3.sa": "https://img.logo.dev/ticker/POSI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PPLA11.sa": "https://img.logo.dev/ticker/PPLA11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PRIO3.sa": "https://img.logo.dev/ticker/PRIO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PRNR3.sa": "https://img.logo.dev/ticker/PRNR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PSSA3.sa": "https://img.logo.dev/ticker/PSSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PSVM11.sa": "https://img.logo.dev/ticker/PSVM11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PTBL3.sa": "https://img.logo.dev/ticker/PTBL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PTNT3.sa": "https://img.logo.dev/ticker/PTNT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "PTNT4.sa": "https://img.logo.dev/ticker/PTNT4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # Q - Q
    "QUAL3.sa": "https://img.logo.dev/ticker/QUAL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # R - R
    "RADL3.sa": "https://img.logo.dev/ticker/RADL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RAIL3.sa": "https://img.logo.dev/ticker/RAIL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RAIZ4.sa": "https://img.logo.dev/ticker/RAIZ4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RANI3.sa": "https://img.logo.dev/ticker/RANI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RAPT3.sa": "https://img.logo.dev/ticker/RAPT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RAPT4.sa": "https://img.logo.dev/ticker/RAPT4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RCSL3.sa": "https://img.logo.dev/ticker/RCSL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RCSL4.sa": "https://img.logo.dev/ticker/RCSL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RDNI3.sa": "https://img.logo.dev/ticker/RDNI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RDOR3.sa": "https://img.logo.dev/ticker/RDOR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "REAG3.sa": "https://img.logo.dev/ticker/REAG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RECV3.sa": "https://img.logo.dev/ticker/RECV3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "REDE3.sa": "https://img.logo.dev/ticker/REDE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RENT3.sa": "https://img.logo.dev/ticker/RENT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RNEW11.sa": "https://img.logo.dev/ticker/RNEW11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RNEW3.sa": "https://img.logo.dev/ticker/RNEW3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RNEW4.sa": "https://img.logo.dev/ticker/RNEW4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "ROMI3.sa": "https://img.logo.dev/ticker/ROMI3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RPAD3.sa": "https://img.logo.dev/ticker/RPAD3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RPAD5.sa": "https://img.logo.dev/ticker/RPAD5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RPMG3.sa": "https://img.logo.dev/ticker/RPMG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RSID3.sa": "https://img.logo.dev/ticker/RSID3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "RSUL4.sa": "https://img.logo.dev/ticker/RSUL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # S - S
    "SANB11.sa": "https://img.logo.dev/ticker/SANB11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SANB3.sa": "https://img.logo.dev/ticker/SANB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SANB4.sa": "https://img.logo.dev/ticker/SANB4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SAPR11.sa": "https://img.logo.dev/ticker/SAPR11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SAPR3.sa": "https://img.logo.dev/ticker/SAPR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SAPR4.sa": "https://img.logo.dev/ticker/SAPR4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SBFG3.sa": "https://img.logo.dev/ticker/SBFG3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SBSP3.sa": "https://img.logo.dev/ticker/SBSP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SCAR3.sa": "https://img.logo.dev/ticker/SCAR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SEER3.sa": "https://img.logo.dev/ticker/SEER3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SEQL3.sa": "https://img.logo.dev/ticker/SEQL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SHOW3.sa": "https://img.logo.dev/ticker/SHOW3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SHUL4.sa": "https://img.logo.dev/ticker/SHUL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SIMH3.sa": "https://img.logo.dev/ticker/SIMH3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SLCE3.sa": "https://img.logo.dev/ticker/SLCE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SMFT3.sa": "https://img.logo.dev/ticker/SMFT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SMTO3.sa": "https://img.logo.dev/ticker/SMTO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SNSY3.sa": "https://img.logo.dev/ticker/SNSY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SNSY5.sa": "https://img.logo.dev/ticker/SNSY5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SOJA3.sa": "https://img.logo.dev/ticker/SOJA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SOND5.sa": "https://img.logo.dev/ticker/SOND5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SOND6.sa": "https://img.logo.dev/ticker/SOND6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SRNA3.sa": "https://img.logo.dev/ticker/SRNA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "STBP3.sa": "https://img.logo.dev/ticker/STBP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SUZB3.sa": "https://img.logo.dev/ticker/SUZB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "SYNE3.sa": "https://img.logo.dev/ticker/SYNE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # T - T
    "TAEE11.sa": "https://img.logo.dev/ticker/TAEE11.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TAEE3.sa": "https://img.logo.dev/ticker/TAEE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TAEE4.sa": "https://img.logo.dev/ticker/TAEE4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TASA3.sa": "https://img.logo.dev/ticker/TASA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TASA4.sa": "https://img.logo.dev/ticker/TASA4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TCSA3.sa": "https://img.logo.dev/ticker/TCSA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TECN3.sa": "https://img.logo.dev/ticker/TECN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TELB3.sa": "https://img.logo.dev/ticker/TELB3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TELB4.sa": "https://img.logo.dev/ticker/TELB4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TEND3.sa": "https://img.logo.dev/ticker/TEND3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TFCO4.sa": "https://img.logo.dev/ticker/TFCO4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TGMA3.sa": "https://img.logo.dev/ticker/TGMA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TIMS3.sa": "https://img.logo.dev/ticker/TIMS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TKNO4.sa": "https://img.logo.dev/ticker/TKNO4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TOTS3.sa": "https://img.logo.dev/ticker/TOTS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TPIS3.sa": "https://img.logo.dev/ticker/TPIS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TRAD3.sa": "https://img.logo.dev/ticker/TRAD3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TRIS3.sa": "https://img.logo.dev/ticker/TRIS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TTEN3.sa": "https://img.logo.dev/ticker/TTEN3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "TUPY3.sa": "https://img.logo.dev/ticker/TUPY3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # U - U
    "UCAS3.sa": "https://img.logo.dev/ticker/UCAS3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "UGPA3.sa": "https://img.logo.dev/ticker/UGPA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "UNIP3.sa": "https://img.logo.dev/ticker/UNIP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "UNIP5.sa": "https://img.logo.dev/ticker/UNIP5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "UNIP6.sa": "https://img.logo.dev/ticker/UNIP6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "USIM3.sa": "https://img.logo.dev/ticker/USIM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "USIM5.sa": "https://img.logo.dev/ticker/USIM5.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "USIM6.sa": "https://img.logo.dev/ticker/USIM6.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # V - V
    "VALE3.sa": "https://img.logo.dev/ticker/VALE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VAMO3.sa": "https://img.logo.dev/ticker/VAMO3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VBBR3.sa": "https://img.logo.dev/ticker/VBBR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VITT3.sa": "https://img.logo.dev/vittia.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VIVA3.sa": "https://img.logo.dev/ticker/VIVA3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VIVR3.sa": "https://img.logo.dev/ticker/VIVR3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VIVT3.sa": "https://img.logo.dev/ticker/VIVT3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VLID3.sa": "https://img.logo.dev/ticker/VLID3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VSTE3.sa": "https://img.logo.dev/ticker/VSTE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VTRU3.sa": "https://img.logo.dev/ticker/VTRU3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VULC3.sa": "https://img.logo.dev/ticker/VULC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "VVEO3.sa": "https://img.logo.dev/viveo.com.br?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # W - W
    "WEGE3.sa": "https://img.logo.dev/ticker/WEGE3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WEST3.sa": "https://img.logo.dev/ticker/WEST3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WHRL3.sa": "https://img.logo.dev/ticker/WHRL3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WHRL4.sa": "https://img.logo.dev/ticker/WHRL4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WIZC3.sa": "https://img.logo.dev/ticker/WIZC3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WLMM3.sa": "https://img.logo.dev/ticker/WLMM3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "WLMM4.sa": "https://img.logo.dev/ticker/WLMM4.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # Y - Y
    "YDUQ3.sa": "https://img.logo.dev/ticker/YDUQ3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",

    # Z - Z
    "ZAMP3.sa": "https://img.logo.dev/ticker/ZAMP3.SA?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "BYDDY":"https://img.logo.dev/byd.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true",
    "STLA":"https://img.logo.dev/stellantis.com?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true"

}


def get_logo_url(ticker):
   
    if not ticker:
        return None
    
    # Verificar se é criptomoeda (formato: XXX-USD ou XXX-USDT)
    ticker_upper = ticker.upper()
    if '-USD' in ticker_upper or '-USDT' in ticker_upper:
        # Extrair o símbolo da cripto (ex: BTC-USD -> btc)
        crypto_symbol = ticker_upper.split('-')[0].lower()
        
   
        crypto_symbols_supported = [
            'btc', 'eth', 'usdc', 'usdt', 'xrp', 'sol', 'doge', 
            'ada', 'matic', 'dot', 'link', 'bnb', 'avax', 'ltc',
            'atom', 'uni', 'xlm', 'algo', 'vet', 'icp', 'fil',
            'aave', 'mkr', 'comp', 'yfi', 'snx', 'crv', 'sushi',
            'trx', 'etc', 'bch', 'xmr', 'dash', 'zec', 'xtz'
        ]
        
        if crypto_symbol in crypto_symbols_supported:
            return f"https://img.logo.dev/crypto/{crypto_symbol}?token=pk_Dhx4NNGHRFe5mo7gEtJaWA&retina=true"
    

    ticker_normalized = ticker.lower()
    

    for key, url in COMPLETE_B3_LOGOS_MAPPING.items():
        if key.lower() == ticker_normalized:
            return url
    
    return None

def add_logo_column_to_data(data, ticker_column='ticker'):

    if not data:
        return data
    
    for row in data:
        ticker = row.get(ticker_column, '')
        logo_url = get_logo_url(ticker)
        
        if logo_url:

            row['ticker'] = f'<a href="/detalhes?ticker={ticker}" style="text-decoration: none; color: inherit;"><div style="display: flex; align-items: center; gap: 8px; cursor: pointer; transition: all 0.2s ease; padding: 4px; border-radius: 6px;" onmouseover="this.style.backgroundColor=\'#f8f9fa\'" onmouseout="this.style.backgroundColor=\'transparent\'"><img src="{logo_url}" alt="{ticker}" style="width: 50px; height: 50px; border-radius: 8px; object-fit: contain; border: 1px solid #e0e0e0; background: white; padding: 3px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);"><span style="font-weight: bold; font-size: 14px;">{ticker}</span></div></a>'
        else:

            ticker_short = ticker.replace('.SA', '').replace('.sa', '')[:4]
            row['ticker'] = f'<a href="/detalhes?ticker={ticker}" style="text-decoration: none; color: inherit;"><div style="display: flex; align-items: center; gap: 8px; cursor: pointer; transition: all 0.2s ease; padding: 4px; border-radius: 6px;" onmouseover="this.style.backgroundColor=\'#f8f9fa\'" onmouseout="this.style.backgroundColor=\'transparent\'"><div style="width: 50px; height: 50px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: 14px; font-weight: bold; color: white; text-shadow: 1px 1px 2px rgba(0,0,0,0.3);">{ticker_short}</div><span style="font-weight: bold; font-size: 14px;">{ticker}</span></div></a>'
    
    return data

def get_table_columns_with_logo(base_columns):

    return base_columns

def get_total_tickers():
   
    return len(COMPLETE_B3_LOGOS_MAPPING)
